story_6/urls.py
from django.contrib import admin
from django.urls import path,include
from vince_story6.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
     path('',include(('vince_story6.urls','vince_story6'),namespace='vince_story6')),
     
    
]

vince_story6/urls.py
from django.urls import re_path
from django.urls import path
#from .views import index,save_status,profile,book_table,get_Json,email_checking,subscribe,display_subscribers,subscribers_table,delete_subscriber,my_view,login,logins,logout
from .views import *

urlpatterns = [
   path('',index, name='index'),
   #path('',status,name='status'),
   path('save_status/',save_status,name='save_status'),
   path('profile/',profile,name='profile'),
   path('story9/',book_table,name='story9'),
   path('getjson/<str:keyword>',get_Json,name='getjson'),
   path('emailcheck/',email_checking,name='emailcheck'),
   path('subscribe/',subscribe,name='subscribe'),
   path('display_subscribers/',display_subscribers,name='display_subscriber'),
   path('challenge10/',subscribers_table,name='challenge10'),
   path('deleted/',delete_subscriber,name='deleted'),
#    path('coba2login/',logins,name='coba2login'),
#    path('logins/',my_view,name='login'),
   path('login/',login,name='login'),
   path('logout/',logout,name='logout'),
   path('flashcard/',flashcard,name='flashcard'),
   path('gettjson/',get_json,name='get_json')
#    path('appippw/mydiary/new/',post_diary,name='postdiary'),
#    path('apippw/mydiary/list/',get_diary,name='getdiary')


]

vince_story6/models.py
from django.db import models
from django.utils import timezone

class Status(models.Model):
    dates = models.DateTimeField(default=timezone.now())
    status = models.TextField(max_length=300)

# class Diary(models.Model):
#     tanggal =  models.DateTimeField(default=timezone.now())
#     catatan = models.TextField(max_length=300)
class Subscriber(models.Model):
    name =  models.CharField(max_length=300)
    email = models.EmailField(max_length=100, null=True, blank=True)
    password =  models.CharField(max_length=100)

    def __str__(self):
        return self.name+"          "+self.email+"          "+self.password

vince_story6/forms.py
from django import forms
from .models import Subscriber



class Status_Form(forms.Form):
    error_messages = {
        'required': 'Please type',
    }
    status_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder': 'status',
        'id':'statuss',
        
    }
    # place_attrs = {
    #     'type': 'text',
    #     'class': 'todo-form-input',
    #     'placeholder':'place'
    # }
    # category_attrs = {
    #     'type': 'text',
    #     'class': 'todo-form-input',
    #     'placeholder':'category'
    # }
    # date_attrs={
    #     'type':'date'
        
    # }

    # category_choices=(
    #     ('indoor','indoor'),
    #     ('outdoor','outdoor'),
    #     ('a bit of both','a bit of both'),
    # )
    
    status = forms.CharField(label='Status', required=True, max_length=67, widget=forms.TextInput(attrs=status_attrs))
    # place = forms.CharField(label='Place', required=True, max_length=27, widget=forms.TextInput(attrs=place_attrs))
    # #category = forms.CharField(label='Category', required=True,max_length=27,choices=category_choices)
    # category = forms.ChoiceField(label='Category', required=True,choices=category_choices)
    # #date = forms.CharField(label='Date', required=True, max_length=27, widget=forms.DateInput(attrs=date_attrs))
    # date = forms.DateField(label='Date',required=True,widget=forms.DateInput(attrs=date_attrs))
    # time = forms.TimeField(label='Time',required=True,widget=forms.TimeInput(attrs={'type':'time'}))
class Login_Form(forms.Form):
    username = forms.CharField(label='username', required=True, max_length=67, widget=forms.TextInput(attrs={
        'placeholder':'username'
    }))
    password = forms.CharField(label='password', required=True, max_length=67, widget=forms.PasswordInput(attrs={
        'placeholder':'password'
    }))



class Subscriber_Form(forms.ModelForm):
 
    class Meta:
        model = Subscriber
        fields =[
            'name',
            'email',
            'password',
        ]
        widgets = {
            'name' : forms.TextInput(attrs={'id':'name'}),
            'email' : forms.EmailInput(attrs={'id':'email'}),
            'password': forms.PasswordInput(attrs={'id':'password'})
            
        }
        

    

vince_story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect,HttpResponse
from django.http import JsonResponse
from django.core.validators import validate_email
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
import story_6.settings as settings
import json
import requests
from .models import Status,Subscriber
from .forms import Status_Form,Subscriber_Form,Login_Form



import os
import json

response ={}
new_response = {}
email_list=[]


# def index(request):
#     return render(request,'html_baru.html',response)


def flashcard(request):
    html = 'flashcard.html'
    # words = {}
    # with open(os.path.join(settings.STATIC_ROOT,"json","words.json"),"r") as f:
    #     words = json.load(f)
    #     print(words)
    return render(request,html )

def get_json(request):
    words = {}
    final_json = {}
    with open(os.path.join(settings.STATIC_ROOT,"json","words.json"),encoding="utf-8") as f:
        words = json.load(f)
   
    final_json = json.dumps(words, ensure_ascii=False)

    return HttpResponse(final_json, content_type="application/json")

def logins(request):
    response['login_form'] = Login_Form
    return render(request,'coba2dikelas.html',response)
def my_view(request):
    pass
def login(request):
    if request.method=="POST":
        request.session['name']=request.POST.get('name')
        #return HttpResponseRedirect('/story9/')
        return book_table(request)
    if request.method=='GET':
        return render(request, 'login.html')
def logout(request):
    request.session.flush()
    return login(request)

def subscribers_table(request):
    return render(request,'subscriberz.html',response)
def book_table(request):
    if request.session.get('name') is not None:
        #response[]
        if request.method == "POST":
            request.session['jml'] = request.POST['jml']
        if request.session.get('jml') is not None:
            response['favourites'] = request.session.get('jml')
            response['name'] = request.session['name']
       
        return render(request,'book_table.html',response)

    return HttpResponseRedirect('/login/')
    #return login(request)
def profile(request):
    #print("Z")
    response['subscriber_form'] = Subscriber_Form
    return render(request, 'homepage.html',response)
def index(request):
    all_status = list(Status.objects.all().order_by('-dates'))
    response['all_status'] = all_status
    response['title'] = 'Add Status'
    response['add_status'] =  Status_Form()
    return render(request,'html_baru.html',response)
def save_status(request):
    form = Status_Form(request.POST or None)
    if(request.method=='POST' and form.is_valid()):
        response['status']= request.POST['status']
        The_Status= Status(
            status=response['status'],
        )
        The_Status.save()
    return HttpResponseRedirect('/')
def display_subscribers(request):
    
    all_subscriber =Subscriber.objects.all()
    
    the_json = {'subscribers':all_subscriber}
    the_json = serializers.serialize("json",all_subscriber)
    the_json = {'subscribers':the_json}
    return JsonResponse(the_json,safe=False)
   

@csrf_exempt
def get_Json(request, keyword="quilting"):
    url ='https://www.googleapis.com/books/v1/volumes?q='
    get_the_json = requests.get(url+keyword)
    the_books = (get_the_json.json())['items']
    actual_json = json.dumps({'items': the_books})
    return HttpResponse(actual_json,content_type="application/json")

def email_checking(request):
    email = request.POST.get('email')
    print(email)
    email_list.append(email)
    print('horeeee')
        
   # all_subscriber = serializers.serialize('json', all_objects)
    subscribers = Subscriber.objects.filter(email=email)
    print(len(subscribers))
    #subscribers = serializers.serialize('json',subscribers)
    if (len(subscribers)>0):
        new_response["message"] = "This email is already registered, Please choose another email"
        new_response["status_code"]=400
        print("wuihhh")
        email=""
        print(222222)
        return JsonResponse(new_response)
    new_response["message"] = "You can use this email!"
    new_response["status_code"] = 200
    print("nih bisa gan")

    return JsonResponse(new_response,status=200)

def delete_subscriber(request):
    print(request.POST.get('emailz'))
    var = request.POST.get('emailz')
    Subscriber.objects.filter(email=var).delete()
    new_response['message'] = "Goodbye! Thank you for unsubscribing!"
    return JsonResponse(new_response)


    
def subscribe(request):
    if(request.method=="POST"):
        #print(email_list)
        subscriber = Subscriber.objects.create(name=request.POST['name'],
                    email=email_list[len(email_list)-1],
                    password=request.POST['password'] )
        subscriber = serializers.serialize("json", [subscriber])
        print(subscriber)
        new_response["message"] = "Subscriber created"
        new_response["subscriber"] = subscriber
        print("ini new response")
        print(new_response)
        return JsonResponse(new_response,status=200)
        

    new_response['message'] = "GET method not allowed"
    return JsonResponse(new_response, status=400)

 



# def post_diary(request):
#     response['catatan'] = request.POST['catatan']
#     The_Diary = Diary(catatan = response['catatan'])
#     The_Diary.save()
#     return HttpResponseRedirect('/')
   
# def get_diary(request):
#     all_diary = list(Diary.objects.all().order_by('-dates'))
#     lis = []
#     data ={'data':lis}
#     for item in all_diary:
#         tanggal = item.tanggal
#         catatan = item.catatan
#         data['data'].append({'tgl':tanggal,'catatan':catatan})
        
#     return JsonResponse(data,safe=False)

        
    



# def display_status(request):
#     all_status = Status.objects.all()
#     response['all_status'] = all_status
#     return status(request)# render(request,'html_baru.html',response)


# Create your views here.



        # try:
        #     validate_email(request.POST['email'])
        #     print('coba dulu')
        #     subscriber = Subscriber.objects.create(name=request.POST['name'],
        #                     email=request.POST['email'],
        #                     password=request.POST['password'] )
        #     print('mantab gan')

        # except:
        #     print("kena exception")
        #     new_response["message"] = 'Wah gabisa yeuh gan'
        #     return JsonResponse(new_response,status=200)
        #     print("kena exception 2")

        # new_response["message"] = "Subscriber created"
        # new_response["subscriber"] = subscriber
        # return JsonResponse(new_response,status=200)

vince_story6/templates/book_table.html
{% extends 'navbar.html' %}
{% load static %}
 {% load staticfiles %}


 {% block content %}
<div  class="container-fluid" id="main">
    <div class="row">
        <div class="col-sm-8">
            <h3>The Books</h3>
        </div>
        <div class="col-sm-4">
                <h3 >Welcome {{name}}</h3>
                <h3 id ="fav" >Favourites: {{favourites}}</h3>
                <button class="btn btn-primary" onclick="signOut();">Sign out</button>
         </div>

    </div>

    <div class ="row">
        <div class = "col-sm-6">
            <input id = "search_box" placeholder="type the name of the book" style="min-width: 250px;">
            <button type="button" class="btn btn-info" id ="search_button" style ="float: right ;">Search</button>

        </div>
    </div>

    <div class="row">
            <div class="table-responsive">
                    <table class="table" >
                        <thead>
                        <th class="col-sm-3">Title</th>
                        <th class="col-sm-3"> Author </th>
                        <th class="col-sm-3"> Publisher </th>
                        <th class="col-sm-3"> Pubilshed Date </th>
                        </thead>
                        <tbody id ="start">

                       </tbody>
                    </table>
                </div>
            </div>
    </div>

    
</div>

<!--<button type="button" class="btn btn-info" id ="unsubs_button" style ="max-width:75px ;">Unsubscribe</button>-->

 {% endblock content %}

vince_story6/templates/coba2dikelas.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
 {% load staticfiles %}
 {% block content %}



 <div class="container-fluid" id="main">

    <div class="row" >
                    
        <div class"col-sm-12";>
            <form id="form" method ="POST" action="{% url 'vince_story6:login' %}"">
                {% csrf_token %}
                {{ login_form.as_p }}
            </form>
            <input  type="submit" value="Submit" id ="submit">
        </div>
    </div>
 </div>


 {% endblock content %} 

vince_story6/templates/flashcard.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
 {% load staticfiles %}

 
    {% block content %}
    
<!-- 
    <div id="wrapperf">
        <div id="divf1">
                <button type="button" class="btn btn-info"  onclick="" style ="float: right ;">Next</button>
        </div>
        <div id="divf2">
                <button type="button" class="btn btn-info"  onclick="" style ="float: right ;">Previous</button>

        </div>
    </div> -->

    <br>
    <br>
    <br>
    <br>

    <div class="row" style=" text-align: center;">
            <div class="col-sm-2 " style=" display: inline-block;">
                <button type="button" class="btn btn-info" id ="info" onclick="next()" style ="float: center ;">Next</button>
            </div>

            
     </div>

     <br>

     <div class="row"   style=" text-align: center;">
      <div class="col-sm-2 " style=" display: inline-block;">
          <button type="button" class="btn btn-info" id ="info" onclick="previous()" style ="float: center ;">Previous</button>
      </div>
    </div> 

     <br>
     <br>

     <article class="flashcard">
      <input id="flashcard-1" type="checkbox" />
      <label for="flashcard-1" id ="flashcardsection" onclick="flip()">
        <section class="front">
          Front of the flashcard!
        </section>
        
    
      </label>
    </article>

    <br>
    <br>


     


     <br>
     <br>


     <div class="row"   style=" text-align: center;">
      <div class="col-sm-2 " style=" display: inline-block;">
          <button type="button" class="btn btn-info" id ="info" onclick="shuffle()" style ="float: center ;">Shuffle</button>
      </div>
</div> 


<br>
<br>



     



    
    {% endblock content %}

vince_story6/templates/html_baru.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
 {% load staticfiles %}

 <!--<head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
         <link rel="stylesheet" type="text/css" href="{% static 'css_nya.css' %}"> 
            <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
           <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> 
    </head> -->
    {% block content %}
    

   
    


        <div class="container-fluid" id="main">

            <div class="row" id="backgreeting">
                    
                <div class = "col-sm-12;">
                        <h4 style="font-size: 45px;" >Hello There !</h4>
                        <h5 style="font-size: 35px;">Feel free to type something</h5>
                </div>
            </div>

            
            <div class="row" id="backgreeting">
                    
                    <div class = "col-sm-12;">
                            <form id="form" method="POST" action="{% url 'vince_story6:save_status' %}">
                                    {% csrf_token %}
                                    {{ add_status.as_p }}
                                    <input  type="submit" value="Submit" id ="submit">
                             </form>
                    </div>
                </div>

               

                <br>
                <div class="row">
                        <div class="col-sm-2 " style="background-color:;">
                            <button type="button" class="btn btn-info" id ="info" onclick="change_theme()" style ="float: right ;">Change Theme</button>
                        </div>
                 </div>
                <br>
                <br>
     <div class="row" style="">
            <div class="col-sm-8">
                    <div>
                            <h3>My Status Timeline</h3>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <th class="col-sm-6">Status</th>
                                    <th class="col-sm-6"> Time Published </th>
                                    </thead>
                                    <tbody>
                                            {% for data in all_status %}
                                        <tr>
                                            <td>{{ data.status }}</td>
                                            <td>{{ data.dates }}</td>
                                        </tr>
                                    {% endfor %}
                                   </tbody>
                                </table>
                            </div>
                        </div>
                
                    
             </div>
             
     </div>



        </div>

        {% endblock content %}
    



<!--    <div>
            <h3>My Status Timeline</h3>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <th class="col-sm-9">Status</th>
                    <th> Time Published </th>
                    </thead>
                    <tbody>
                    {% for foo in message %}
                        <tr>
                            <td>{{ foo.statusField }}</td>
                            <td>{{ foo.timeField }}</td>
                        </tr>
                    {% endfor %}
                   </tbody>
                </table>
            </div>
        </div>

        <div class="col-sm-12">
                <a  style="font-size: 20px"> Status : {{ data.status }}</a><br>
                <a  style="font-size: 20px"> Time : {{ data.dates }}</a><br>
               
                <br>
                <br>
                    
             </div> -->

vince_story6/templates/landing_page.html
<!DOCTYPE html>
{% load static %}
 {% load staticfiles %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="stylesheet" type="text/css" href="{% static 'css_nya.css' %}"> 
        <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> 
</head>

<body>
               
               <div class="container-fluid" id = "main">
                    <div class="row">
                        <div class="col-sm-12">
                               <h1 id="head1">Hello There !</h1>
                               <h2 id="head2" >Feel free to type somethinggggg</h2>
                        </div>
               
                    </div>

                    <div class="row">
                            <div class="col-sm-2 " style="background-color:;">
                                <button type="button" class="btn btn-info" id ="info" onclick="change_theme()">Change Theme</button>
                            </div>
                        </div>
               
                    <div class="row">
                        <div class="col-sm-9">
                               <form id="form" method="POST" action="{% url 'vince_story6:save_status' %}">
                                       {% csrf_token %}
                                       {{ add_status.as_p }}
                                       <input  type="submit" value="Submit">
                                </form>
               
                        </div>
                        
                        
                   </div>
                   
                </div> 
</body>

vince_story6/templates/login.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
 {% load staticfiles %}

 {% block content %}

 <div class="container">

      <!-- <section class="back">
                Back of the flashcard!
              </section> -->


    <h1>Please Complete your login to continue</h1>
    <div class="g-signin2" data-onsuccess="onSignIn"></div>

</div>



 {% endblock content %} 

vince_story6/templates/navbar.html
<!DOCTYPE html>
{% load static %}
 {% load staticfiles %}
<head>
      
    <title>Homepage</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    
   <link rel="stylesheet" type="text/css" href="{% static 'css.css' %}"> 
    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> 
    <script src="{% static 'js/theme.js'  %}"></script> 
    <script src="{% static 'js/email.js'  %}"></script> 
    <script src="{% static 'js/flashcard.js'  %}"></script> 
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>

    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id" content="267233680696-q2e4tu6gp9e96dqvkv9fu7s9fd46lqf1.apps.googleusercontent.com"> 
  <!-- <meta name="google-signin-client_id" content=" 267233680696-buk6jb6vnd8vj0sko3p32n2f6gmsf3da.apps.googleusercontent.com"> -->

   
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  

</head>

<body onload="myFunction()" >
    <div>

        <nav class="navbar navbar-expand-lg navbar-light bg-dark ">
           
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav ml-auto">
            
              <li><a class="nav-item nav-link " href="{% url 'vince_story6:index' %}"  style="color:white;padding: 10px 25px;">Home</a></li> 
               <li><a class="nav-item nav-link" href="{% url 'vince_story6:profile' %}"style="color:white;  margin: 0px;padding: 10px 25px;">Profile</a></li> 
               <li><a class="nav-item nav-link" href="{% url 'vince_story6:story9' %}"style="color:white;  margin: 0px;padding: 10px 25px;">Story11</a></li> 
               <li><a class="nav-item nav-link" href="{% url 'vince_story6:challenge10' %}"style="color:white;  margin: 0px;padding: 10px 25px;">Challenge 10</a></li> 
               <li><a class="nav-item nav-link" href="{% url 'vince_story6:flashcard' %}"style="color:white;  margin: 0px;padding: 10px 25px;">Flashcard</a></li> 
               <!--{% url 'vince_story6:story9' %}-->
              
               
             </div>
           </div>
         </nav>


   </div> 
   
   <div id="loader"></div>
 <div style="display:none;" id="myDiv" class="animate-bottom"> 
 
   {% block content %}
   {% endblock %}

</body>



        

vince_story6/templates/subscriberz.html
{% extends 'navbar.html' %}
{% load static %}
 {% load staticfiles %}


 {% block content %}
<div  class="container-fluid" id="main">
    <div class="row">
        <div class="col-sm-8">
            <h3>The Subscribers</h3>
        </div>
    </div>

    <div class="row">
            <div class="table-responsive">
                    <table class="table" >
                        <thead>
                        <th class="col-sm-3">Name</th>
                        <th class="col-sm-3"> Email </th>
                        </thead>
                        {% csrf_token %}
                        <tbody id ="start_subs">

                       </tbody>
                    </table>
                </div>
            </div>
    </div>
</div>

 {% endblock content %}